### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by scoobydeezy** [brakacai/discord-ghost#29]
MacOS - running gives me this error:

```
(node:61571) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'characterActivities' of undefined
    at Client.getCurrentCharacterId (/snapshot/discord-ghost/dist/Client.js:0:0)
    at Client.<anonymous> (/snapshot/discord-ghost/dist/Client.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/discord-ghost/dist/Client.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:61571) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

**Comment by louis-bompart** [comment]
Did you start the game before launching the program?

**Comment by scoobydeezy** [comment]
No - which I suppose turns this into a feature request. It would be great if the script could handle offline profiles and give a "This guardian is offline" message or similar.

**Comment by louis-bompart** [comment]
relates to #38 we're investigating a proper way to do it :)

**Comment by BoostdDSM** [comment]
This is the exact issue I have. But I was in-game before launching the program.

**Comment by louis-bompart** [comment]
Are you BoostdDSM on Playstation and Boostd DSM on Xbox? If yes, on what platform are you playing Destiny 2?
