### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by ghost** [brakacai/discord-ghost#48]
Using Windows, worked on initial launch then an hour later this shows up:
(node:4192) UnhandledPromiseRejectionWarning: Error: child "activity" fails because [child "state" fails because ["state" length must be less than or equal to 128 characters long]]
    at RPCClient._onRpcMessage (C:\snapshot\discord-ghost\node_modules\discord-rpc\src\client.js:171:19)
    at IPCTransport.emit (events.js:189:13)
    at connect.socket.on.decode (C:\snapshot\discord-ghost\node_modules\discord-rpc\src\transports\ipc.js:134:18)
    at decode (C:\snapshot\discord-ghost\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.connect.socket.on (C:\snapshot\discord-ghost\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:189:13)
    at emitReadable_ (_stream_readable.js:535:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:4192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)

And repeats itself nonstop. I do have the game open (PS4)

**Comment by louis-bompart** [comment]
Do you use the Windows client or the web app for Discord?

**Comment by ghost** [comment]
Windows client.

**Comment by pjuhel** [comment]
Does restarting the service helped in anyway ( closing the console and launching start.exe again ) or is the error persisting ?

**Comment by louis-bompart** [comment]
Nvm! I misread your log I found the issue, will patch it!

**Comment by louis-bompart** [comment]
> DEV NOTE: need to make sure that state field length is below or equal 128 characters. Need to find specs about that and sanitize the other fields as well

**Comment by ghost** [comment]
I have tried restarting, and it just doesn't work at all anymore

**Comment by pjuhel** [comment]
We will look into your issue. 

Until a fix is provided, i suggest you delete the configuration file the app created ( C:/Users/yourusername/discord-ghost ) to make a true " fresh start ", this could temporarily solve your problem. Open it and save your API key which is saved in here if you don't have it save somewhere else already!
