### ISSUE TITLE
I don't know what to title this

### ISSUE THREAD

**Issue by DarthIgsion** [brakacai/discord-ghost#59]
(node:1780) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substr' of undefined
    at DiscordRPC.sanitizeActivity (C:\snapshot\discord-ghost\dist\DiscordRPC.js:0:0)
    at DiscordRPC.<anonymous> (C:\snapshot\discord-ghost\dist\DiscordRPC.js:0:0)
    at Generator.next (<anonymous>)
    at __awaiter (C:\snapshot\discord-ghost\dist\DiscordRPC.js:0:0)
    at new Promise (<anonymous>)
    at __awaiter (C:\snapshot\discord-ghost\dist\DiscordRPC.js:0:0)
    at DiscordRPC.setActivity (C:\snapshot\discord-ghost\dist\DiscordRPC.js:0:0)
    at Client.<anonymous> (C:\snapshot\discord-ghost\dist\Client.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\discord-ghost\dist\Client.js:0:0)
(node:1780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
I have no clue what this is or how to fix it. This happens when I tried to run the program after imputing my API Key and PSN.

**Comment by louis-bompart** [comment]
Oh snap! I messed up hang in there, it'll be fixed in ten minutes.

**Comment by DarthIgsion** [comment]
So what do I do to fix the issue?

**Comment by louis-bompart** [comment]
Download the new version, the package will pop up anytime soon.
You can track the creation of the app here https://travis-ci.com/brakacai/discord-ghost/builds/118147954
As soon as they're all green it'll be done.

It'll be available there: https://github.com/brakacai/discord-ghost/releases/tag/v1.1.22

**Comment by louis-bompart** [comment]
@DarthIgsion it's up https://github.com/brakacai/discord-ghost/releases/tag/v1.1.22
Can you confirm that the issue is resolved ?

**Comment by DarthIgsion** [comment]
I can confirm that the issue has been resolved, thank you for your speedy resolution to my problem.

**Comment by louis-bompart** [comment]
You're very welcome, thanks for your report!
