### ISSUE TITLE
issue logging in and displaying from ps4

### ISSUE THREAD

**Issue by IAMsassyninja** [brakacai/discord-ghost#61]
I tried to link PSN and just get this:

(node:12736) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substr' of undefined
    at DiscordRPC.sanitizeActivity (C:\snapshot\discord-ghost\dist\DiscordRPC.js:0:0)
    at DiscordRPC.<anonymous> (C:\snapshot\discord-ghost\dist\DiscordRPC.js:0:0)
    at Generator.next (<anonymous>)
    at __awaiter (C:\snapshot\discord-ghost\dist\DiscordRPC.js:0:0)
    at new Promise (<anonymous>)
    at __awaiter (C:\snapshot\discord-ghost\dist\DiscordRPC.js:0:0)
    at DiscordRPC.setActivity (C:\snapshot\discord-ghost\dist\DiscordRPC.js:0:0)
    at Client.<anonymous> (C:\snapshot\discord-ghost\dist\Client.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\discord-ghost\dist\Client.js:0:0)
(node:12736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)

**Comment by louis-bompart** [comment]
Hi @IAMsassyninja, try the latest version https://github.com/brakacai/discord-ghost/releases/latest.

It's been fixed, if I'm not mistaken. See #59

**Comment by louis-bompart** [comment]
Tell me if updating fixes your issue :)

**Comment by IAMsassyninja** [comment]
I thought I had current version, but I redownloaded anyways to make sure. I
deleted some temporarly files, and reentered the API and PSN. Now the CMD
window just force closes instantly. Maybe I am not smart enough lol, but
thank you for the help!

**Comment by louis-bompart** [comment]
You've downloaded 1.1.23 right?

Try the following:
Open a powershell in the folder where you unzipped everything (where start.exe is)
Shift right click in it, select Open Powershell Windows.
In the powershell, type `.\start.exe`. press enter. Tell me what happens/ what's prompt.

**Comment by louis-bompart** [comment]
Close for inactivity
